### ISSUE TITLE
Setup fails due to eslint-plugin-import@"^2.25.3" from eslint-config-airbnb-typescript@17.0.0 dependency error

### ISSUE THREAD

**Issue by S0PEX** [josh-stillman/lintier#13]
Hey,

it seems like the e2e test work fine but `npx linter` fails on a fresh project that just had `npm init` run before.
The error is that it seems that `eslint-plugin-import` and `eslint-config-airbnb-typescript` can fully resolve the dependencies.

Edit: When using yarn `yarn init` and then ending a random dep so that `yarn.lock` is created `npx linter` works without any issues, seems to be an `npm issue`?
Log:
```
PS A:\Git\Notification-Bot> npx lintier
? Install which plugins? Node
? Install AirBnb Style Guide Config? Yes
? Install lint-staged? Yes
✔ Installing dependencies...
/ Installing airbnb...Error: Command failed with exit code 1: npm install eslint-config-airbnb-typescript -E -D
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: Notification-Bot@1.0.0
npm ERR! Found: eslint-plugin-import@2.25.2
npm ERR! node_modules/eslint-plugin-import
npm ERR!   dev eslint-plugin-import@"2.25.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer eslint-plugin-import@"^2.25.3" from eslint-config-airbnb-typescript@17.0.0
npm ERR! node_modules/eslint-config-airbnb-typescript
npm ERR!   dev eslint-config-airbnb-typescript@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\Artur\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Artur\AppData\Local\npm-cache\_logs\2022-04-16T12_25_21_182Z-debug-0.log
    at makeError (C:\Users\Artur\AppData\Local\npm-cache\_npx\c474b1945def7d56\node_modules\execa\lib\error.js:59:11)
    at handlePromise (C:\Users\Artur\AppData\Local\npm-cache\_npx\c474b1945def7d56\node_modules\execa\index.js:114:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  shortMessage: 'Command failed with exit code 1: npm install eslint-config-airbnb-typescript -E -D',
  command: 'npm install eslint-config-airbnb-typescript -E -D',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'npm ERR! code ERESOLVE\n' +
    'npm ERR! ERESOLVE unable to resolve dependency tree\n' +
    'npm ERR! \n' +
    'npm ERR! While resolving: Notification-Bot@1.0.0\n' +
    'npm ERR! Found: eslint-plugin-import@2.25.2\n' +
    'npm ERR! node_modules/eslint-plugin-import\n' +
    'npm ERR!   dev eslint-plugin-import@"2.25.2" from the root project\n' +
    'npm ERR! \n' +
    'npm ERR! Could not resolve dependency:\n' +
    'npm ERR! peer eslint-plugin-import@"^2.25.3" from eslint-config-airbnb-typescript@17.0.0\n' +
    'npm ERR! node_modules/eslint-config-airbnb-typescript\n' +
    'npm ERR!   dev eslint-config-airbnb-typescript@"*" from the root project\n' +
    'npm ERR! \n' +
    'npm ERR! Fix the upstream dependency conflict, or retry\n' +
    'npm ERR! this command with --force, or --legacy-peer-deps\n' +
    'npm ERR! to accept an incorrect (and potentially broken) dependency resolution.\n' +
    'npm ERR! \n' +
    'npm ERR! See C:\\Users\\Artur\\AppData\\Local\\npm-cache\\eresolve-report.txt for a full report.\n' +
    '\n' +
    'npm ERR! A complete log of this run can be found in:\n' +
    'npm ERR!     C:\\Users\\Artur\\AppData\\Local\\npm-cache\\_logs\\2022-04-16T12_25_21_182Z-debug-0.log',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
\ Installing airbnb...Terminate batch job (Y/N)? y
```

I have tried to manually rerun the commands with `--force` without any success.

Regards,
Artur

**Comment by josh-stillman** [comment]
Hi @S0PEX, thanks for raising the issue.  I wasn't able to replicate this locally on mac osx and the latest npm version.  (I do see different versions of `eslint-plugin-import` listed as the peerdeps of `eslint-config-airbnb-base` and `eslint-config-airbnb-typescript`, but that didn't present any issues for me locally.). Could you try updating your npm version (if applicable) and/or perhaps [clearing your npx cache](https://stackoverflow.com/questions/63510325/how-can-i-clear-the-central-cache-for-npx) and letting me know if that fixes it?

**Comment by S0PEX** [comment]
Hey, updating npm and cleaning the cache fixed the issue for me.
Sorry for the late response btw.

Thanks for your help.
